version: "3.8"

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000" # API Gateway is exposed on port 3000
    depends_on:
      - user-service
      - order-service
      - payment-service
      - rabbitmq

  # User Service
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001" # User Service is exposed on port 3001
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Order Service
  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002" # Order Service is exposed on port 3002
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Payment Service
  payment-service:
    build: ./services/payment-service
    ports:
      - "3003:3003" # Payment Service is exposed on port 3003
    depends_on:
      rabbitmq:
        condition: service_healthy

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Payment Processor (Message Consumer)
  payment-processor:
    build: ./message-queue
    container_name: payment-processor
    command: ["node", "payment-processor.js"]
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Notification Service
  notification-service:
    build: ./message-queue
    container_name: notification-service
    command: ["node", "notification-service.js"]
    depends_on:
      rabbitmq:
        condition: service_healthy
